Install nexusrpc from GitHub (#966)
* Install nexus-rpc from GitHub

* Respond to upstream: {get,set}_operation_definition -> {get,set}_operation

* Respond to upstream: do not use get_operation_factory

* Don't warn on lack of type annotations on op handler

* Nexus typing fixes

diff --git a/.github/workflows/build-binaries.yml b/.github/workflows/build-binaries.yml
--- a/.github/workflows/build-binaries.yml
+++ b/.github/workflows/build-binaries.yml
@@ -74,3 +74,8 @@ jobs:
         with:
           name: packages-${{ matrix.package-suffix }}
           path: dist
+
+      - name: Deliberately fail to prevent releasing nexus-rpc w/ GitHub link in pyproject.toml
+        run: |
+          echo "This is a deliberate failure to prevent releasing nexus-rpc with a GitHub link in pyproject.toml"
+          exit 1
